---
- name: Do some Script 2 things
  hosts: default
  become: yes
  
  tasks:
    - name: Creating a file with content
      copy:
        dest: "/script2.logs"
        content: |
          I am script2
          Nothing to see here...